---
Name: gridfieldajaxrefresh
Before: 'app/*'
After:
  - 'framework/*'
  - 'cms/*'
---

GridFieldConfig_Base:
  extensions:
    - GridFieldAjaxRefresh_Base

GridFieldConfig_RecordEditor:
  extensions:
    - GridFieldAjaxRefresh_RecordEditor
